import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { Toaster } from '@/components/ui/sonner'
import { Card } from '@/components/ui/card'
import { signOut } from '@/lib/actions/authSupabase'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const sessionCookie = cookieStore.get('session')?.value
  const parsedSession = sessionCookie ? JSON.parse(sessionCookie) : null

  if (
    parsedSession &&
    (parsedSession.date - Date.now()) / (1000 * 60 * 60 * 24) > 7
  ) {
    cookieStore.delete('session')
  }

  if (!parsedSession) await signOut()

  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          flex
          justify-center
          py-16
          select-none
      `}
      >
        <Card
          className="
            grid
            grid-cols-1
            md:grid-cols-[1fr_auto_1fr]
            px-16
            py-12
          "
        >
          <div />
          {children}
          <Toaster />
          <div />
        </Card>
      </body>
    </html>
  )
}
