import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          flex
          justify-center
          py-16
      `}
      >
        <main
          className="
            grid
            grid-cols-1
            md:grid-cols-[1fr_auto_1fr]
            px-16
            py-12
            md:border
            border-dashed
            border-neutral-400
            rounded-lg
          "
        >
          <div />
          {children}
          <Toaster />
          <div />
        </main>
      </body>
    </html>
  )
}
